/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A loaded and decrypted murk vault. */
export declare class Vault {
  /**
   * Get a single decrypted secret value. Resolution order: a personal scoped
   * override, then a named-group value we can read, then the shared value.
   *
   * Internally, vault state stores values in `Zeroizing<String>` so plaintext
   * is wiped from memory when dropped. Crossing the napi boundary into a
   * JavaScript `String` requires copying the plaintext into a regular Rust
   * `String`; the V8 garbage collector owns it from there and zeroize cannot
   * follow. This is a known leak in the JS bindings — see THREAT_MODEL.md.
   *
   * When the loaded identity is a granted agent, the vault's agent policy is
   * enforced before the value is returned — the same gate the CLI applies at
   * `agent exec`. Throws if policy forbids the key. For an operator identity
   * this is a no-op.
   */
  get(key: string): string | null
  /**
   * Export all secrets as an object. Scoped values override shared values.
   *
   * See `get` for the zeroize caveat — the returned `HashMap` holds plain
   * `String` plaintext, not `Zeroizing<String>`.
   *
   * For a granted agent, the vault's agent policy is enforced over the full
   * key set first (mirroring `murk agent exec`): if any resolvable key is
   * outside the policy, the whole export throws rather than returning a
   * partial object. For an operator identity this is a no-op.
   */
  export(): Record<string, string>
  /** List all key names. */
  keys(): Array<string>
  /** Number of secrets in the vault. */
  get length(): number
  /** Check if a key exists. */
  has(key: string): boolean
  /**
   * Store a secret. Mirrors `murk add`: the value is encrypted to the tier's
   * recipients and the vault is re-signed and written back to disk under an
   * exclusive lock, so it is safe against concurrent writers.
   *
   * `tier` selects the destination — `"everyone"` (default, shared to all
   * recipients), `"me"` (a personal value encrypted to the caller only), or a
   * group name (encrypted to that group's members; the caller must be a
   * member). An existing key is overwritten in place.
   *
   * PLAINTEXT CAVEAT: unlike the read path — where plaintext only ever appears
   * *after* decryption — a write means the caller already holds the secret as a
   * JavaScript `String` before this call. That string lives in V8's heap, is
   * copied across the napi boundary into a Rust `String`, and is not zeroized on
   * either side. See `get` and THREAT_MODEL.md.
   *
   * Agent policy is enforced exactly as on the read path: if the loaded
   * identity is a granted agent (or the operator has opted into self-scope),
   * the resulting key must satisfy the vault's agent allow-tag policy and the
   * grant must be unexpired — otherwise the write throws and nothing is saved.
   * For a plain operator identity this is a no-op.
   */
  add(key: string, value: string, options?: AddOptions | undefined | null): void
  /**
   * Update a secret's description (and optionally its tags/example) in the
   * vault schema. Mirrors `murk describe`. Does not touch the secret value;
   * a key with no value becomes a documented-but-unset entry.
   *
   * Agent policy is enforced over the key exactly as in `add`.
   */
  describe(key: string, description: string, options?: DescribeOptions | undefined | null): void
}

/** One-liner: load the vault and store a secret. See `Vault.add`. */
export declare function add(key: string, value: string, options?: AddOptions | undefined | null, vaultPath?: string | undefined | null): void

/**
 * Options for [`Vault::add`]. All fields are optional; an omitted `tier`
 * defaults to `everyone` (the shared value).
 */
export interface AddOptions {
  /** `"everyone"` (default), `"me"` (personal scoped), or a group name. */
  tier?: string
  /** Human-readable description recorded in the vault schema. */
  desc?: string
  /** Tags recorded on the key — the unit the agent allow-tag policy gates on. */
  tags?: Array<string>
}

/** Options for [`Vault::describe`]. All fields are optional. */
export interface DescribeOptions {
  /** Tags to set on the key (replaces existing tags when non-empty). */
  tags?: Array<string>
  /** Example value recorded in the schema (for `.env.example`-style docs). */
  example?: string
}

/** One-liner: load the vault and export all secrets as an object. */
export declare function exportAll(vaultPath?: string | undefined | null): Record<string, string>

/** One-liner: load the vault and get a single key. */
export declare function get(key: string, vaultPath?: string | undefined | null): string | null

/**
 * Whether a decryption identity (`MURK_KEY` / `MURK_KEY_FILE`) is available in
 * the environment — i.e. whether `load` can decrypt. This does not check
 * whether a secret exists; use `Vault.has` / `Vault.keys` for that.
 */
export declare function hasIdentity(): boolean

/** Load a murk vault. Reads MURK_KEY from the environment. */
export declare function load(vaultPath?: string | undefined | null): Vault
