#!/usr/bin/env bash
# One-command version bump across every place murk's version lives, so the
# manual multi-file edit that let node/package-lock.json drift can't recur.
#
# Usage: scripts/bump-version.sh <x.y.z>
set -euo pipefail

ver="${1:?usage: scripts/bump-version.sh <x.y.z>}"
cd "$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"

# Rust: single source of truth is [workspace.package] version; every crate
# inherits it via `version.workspace = true`. Replace only the version line
# inside that section (the `-i.bak` form works on both BSD and GNU sed).
sed -i.bak -e '/^\[workspace\.package\]/,/^\[/ s/^version = ".*"/version = "'"$ver"'"/' Cargo.toml
rm -f Cargo.toml.bak

# Node bindings: `npm version` updates package.json AND package-lock.json in
# lockstep — the step whose absence caused the drift. It only rewrites the
# version fields, not the dependency tree.
( cd node && npm version "$ver" --no-git-tag-version --allow-same-version >/dev/null )

# node/index.js is generated by napi-rs and embeds the package version in
# every native-binding version-check block (the `!== '<ver>'` comparison and
# the `expected <ver> but got` half of its error message). `npm version`
# above only rewrites package.json/package-lock.json, so without this,
# index.js would keep enforcing the pre-bump version until someone reruns
# `napi build` — check-versions.cjs now catches that drift, so fix it here.
sed -i.bak -E \
  -e "s/(bindingPackageVersion !== ')[^']+(')/\\1${ver}\\2/g" \
  -e "s/(mismatch, expected )[^ ]+( but got)/\\1${ver}\\2/g" \
  node/index.js
rm -f node/index.js.bak

# Sync Cargo.lock to the new workspace version (and sanity-check the build).
cargo check --quiet

# The fuzz crate is a separate workspace whose lockfile pins murk-cli by path,
# so the root `cargo check` above never touches it. `cargo metadata` re-resolves
# and rewrites fuzz/Cargo.lock without building the nightly-only fuzz targets.
cargo metadata --manifest-path fuzz/Cargo.toml --format-version 1 >/dev/null

# Verify everything agrees before handing back.
node scripts/check-versions.cjs
echo "bumped murk to $ver"
