.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH add 1  "add " 
.SH NAME
add \- Add a member to a group
.SH SYNOPSIS
\fBmurk group add\fR [\fB\-\-vault\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fB\-\-member\fR> <\fINAME\fR> 
.SH DESCRIPTION
Add a member to a group
.SH OPTIONS
.TP
\fB\-\-member\fR \fI<MEMBER>\fR
Recipient pubkey or display name to add
.TP
\fB\-\-vault\fR \fI<VAULT>\fR [default: .murk]
Vault filename
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Group name
