.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH set 1  "set " 
.SH NAME
set \- Set the agent allow\-list: agents may only receive secrets carrying one of these tags
.SH SYNOPSIS
\fBmurk policy set\fR [\fB\-\-vault\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fB\-\-allow\-tag\fR> 
.SH DESCRIPTION
Set the agent allow\-list: agents may only receive secrets carrying one of these tags
.SH OPTIONS
.TP
\fB\-\-allow\-tag\fR \fI<ALLOW_TAG>\fR
Tag agents are allowed to receive (repeatable, required)
.TP
\fB\-\-vault\fR \fI<VAULT>\fR [default: .murk]
Vault filename
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
