.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH generate 1  "generate " 
.SH NAME
generate \- Generate a random secret and store it
.SH SYNOPSIS
\fBmurk generate\fR [\fB\-\-length\fR] [\fB\-\-hex\fR] [\fB\-\-desc\fR] [\fB\-\-example\fR] [\fB\-\-group\fR] [\fB\-\-tag\fR] [\fB\-\-vault\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIKEY\fR> 
.SH DESCRIPTION
Generate a random secret and store it
.SH OPTIONS
.TP
\fB\-\-length\fR \fI<LENGTH>\fR [default: 32]
Length in bytes (default 32)
.TP
\fB\-\-hex\fR
Output as hex instead of base64
.TP
\fB\-\-desc\fR \fI<DESC>\fR
Description for this key
.TP
\fB\-\-example\fR \fI<EXAMPLE>\fR
Example value
.TP
\fB\-\-group\fR \fI<GROUP>\fR
Who can read it: a group name, `everyone` (default), or `me`
.TP
\fB\-\-tag\fR \fI<TAG>\fR
Tag for grouping (repeatable)
.TP
\fB\-\-vault\fR \fI<VAULT>\fR [default: .murk]
Vault filename
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIKEY\fR>
Secret key name
